In [15]:
import pandas as pd
from pandas import DataFrame, Series

In [26]:
year = range(2000, 2019)

In [29]:
df = pd.read_csv("annual_aqi_by_county_1999.csv")
for y in year:
    df2 = pd.read_csv("annual_aqi_by_county_" + str(y) + ".csv")
    df = pd.concat([df, df2])

,State,County,Year,Days with AQI,Good Days,Moderate Days,Unhealthy for Sensitive Groups Days,Unhealthy Days,Very Unhealthy Days,Hazardous Days,Max AQI,90th Percentile AQI,Median AQI,Days CO,Days NO2,Days Ozone,Days SO2,Days PM2.5,Days PM10
0,Alabama,Clay,1999,273,117,97,49,10,0,0,182,122,58,0,0,210,0,63,0
1,Alabama,Colbert,1999,359,276,71,11,1,0,0,166,73,11,0,0,0,284,75,0
2,Alabama,DeKalb,1999,114,35,74,5,0,0,0,134,88,59,0,0,0,0,105,9
3,Alabama,Elmore,1999,241,157,71,12,1,0,0,151,87,45,0,0,241,0,0,0
4,Alabama,Escambia,1999,58,57,1,0,0,0,0,52,35,20,0,0,0,0,0,58
5,Alabama,Etowah,1999,59,56,3,0,0,0,0,56,46,27,0,0,0,0,0,59
6,Alabama,Houston,1999,74,18,53,3,0,0,0,144,92,64,0,0,0,0,70,4
7,Alabama,Jackson,1999,354,279,52,21,2,0,0,154,85,14,0,0,0,354,0,0
8,Alabama,Jefferson,1999,365,19,235,71,34,6,0,273,152,82,36,0,66,16,223,24
9,Alabama,Lawrence,1999,365,215,102,41,7,0,0,182,108,44,0,0,210,103,52,0
10,Alabama,Madison,1999,364,201,115,33,15,0,0,182,105,48,7,0,275,0,68,14
11,Alabama,Marengo,1999,54,52,2,0,0,0,0,51,41,26,0,0,0,0,0,54
12,Alabama,Mobile,1999,365,128,129,97,11,0,0,179,129,65,0,0,120,172,71,2
13,Alabama,Montgomery,1999,307,147,133,22,5,0,0,200,97,51,0,0,170,0,97,40
14,Alabama,Morgan,1999,102,30,65,5,2,0,0,155,96,64,0,0,0,0,92,10
15,Alabama,Pike,1999,57,57,0,0,0,0,0,42,31,19,0,0,0,0,0,57
16,Alabama,Russell,1999,104,22,74,7,1,0,0,153,98,64,0,0,0,0,98,6
17,Alabama,Shelby,1999,271,103,108,37,20,3,0,212,133,59,0,0,204,0,57,10
18,Alabama,Sumter,1999,259,152,96,11,0,0,0,143,78,46,0,0,169,0,90,0
19,Alabama,Talladega,1999,114,37,61,16,0,0,0,137,105,60,0,0,0,0,102,12
20,Alabama,Tuscaloosa,1999,115,26,82,7,0,0,0,125,93,61,0,0,0,0,106,9
21,Alabama,Walker,1999,103,37,59,7,0,0,0,116,84,60,0,0,0,0,88,15
22,Alaska,Anchorage,1999,313,252,58,2,1,0,0,158,60,33,134,0,0,0,69,110
23,Alaska,Denali,1999,362,359,3,0,0,0,0,65,44,31,0,0,358,0,4,0
24,Alaska,Fairbanks North Star,1999,237,188,45,4,0,0,0,130,65,30,174,0,0,0,53,10
25,Alaska,Juneau,1999,120,118,2,0,0,0,0,83,29,9,0,0,0,0,62,58
26,Alaska,Ketchikan Gateway,1999,12,12,0,0,0,0,0,30,21,12,0,0,0,0,12,0
27,Alaska,Matanuska-Susitna,1999,120,101,15,3,1,0,0,154,67,16,0,0,0,0,79,41
28,Arizona,Cochise,1999,355,232,118,5,0,0,0,129,74,47,0,0,323,0,8,24
29,Arizona,Coconino,1999,361,214,132,15,0,0,0,136,84,49,0,0,349,0,12,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1008,Wisconsin,Milwaukee,2018,182,130,49,3,0,0,0,122,65,43,1,8,105,0,68,0
1009,Wisconsin,Oneida,2018,181,176,5,0,0,0,0,69,24,1,0,0,0,181,0,0
1010,Wisconsin,Outagamie,2018,181,135,41,5,0,0,0,123,69,44,0,0,116,16,49,0
1011,Wisconsin,Ozaukee,2018,179,149,26,4,0,0,0,140,64,41,0,0,132,0,47,0
1012,Wisconsin,Racine,2018,129,102,21,5,1,0,0,156,74,43,0,0,129,0,0,0
1013,Wisconsin,Rock,2018,133,111,21,1,0,0,0,133,64,41,0,0,133,0,0,0
1014,Wisconsin,Sauk,2018,181,146,34,1,0,0,0,122,64,43,0,0,126,0,55,0
1015,Wisconsin,Sheboygan,2018,134,105,22,6,1,0,0,169,77,44,0,0,134,0,0,0
1016,Wisconsin,Taylor,2018,241,212,29,0,0,0,0,93,51,41,0,0,211,0,30,0
1017,Wisconsin,Vilas,2018,181,159,22,0,0,0,0,100,51,42,0,0,129,0,52,0
1018,Wisconsin,Walworth,2018,130,100,28,2,0,0,0,126,74,42,0,0,130,0,0,0
1019,Wisconsin,Waukesha,2018,181,141,37,3,0,0,0,122,64,42,0,0,111,0,70,0
1020,Wyoming,Albany,2018,251,132,116,3,0,0,0,115,77,50,0,1,216,0,14,20
1021,Wyoming,Big Horn,2018,249,216,33,0,0,0,0,84,54,42,0,0,249,0,0,0
1022,Wyoming,Campbell,2018,273,215,56,1,1,0,0,167,56,42,0,0,130,0,1,142
1023,Wyoming,Carbon,2018,181,148,33,0,0,0,0,87,58,44,0,8,168,5,0,0
1024,Wyoming,Converse,2018,273,258,15,0,0,0,0,67,48,37,1,0,173,91,4,4
1025,Wyoming,Fremont,2018,212,157,55,0,0,0,0,91,64,46,0,0,173,0,28,11
1026,Wyoming,Johnson,2018,44,35,9,0,0,0,0,64,54,47,0,0,44,0,0,0
1027,Wyoming,Laramie,2018,212,182,30,0,0,0,0,93,54,43,0,6,162,0,41,3
1028,Wyoming,Lincoln,2018,273,262,11,0,0,0,0,82,36,17,0,0,0,0,0,273
1029,Wyoming,Natrona,2018,211,165,46,0,0,0,0,84,58,44,0,10,167,1,32,1
1030,Wyoming,Park,2018,92,87,5,0,0,0,0,85,36,15,0,0,0,0,68,24
1031,Wyoming,Platte,2018,30,28,2,0,0,0,0,55,48,12,0,0,0,0,0,30
1032,Wyoming,Sheridan,2018,273,176,95,2,0,0,0,108,67,47,0,0,232,0,41,0
1033,Wyoming,Sublette,2018,273,160,113,0,0,0,0,97,71,49,0,0,273,0,0,0
1034,Wyoming,Sweetwater,2018,273,189,78,5,1,0,0,163,67,44,0,1,145,66,22,39
1035,Wyoming,Teton,2018,253,183,69,1,0,0,0,106,64,46,0,0,225,0,27,1
1036,Wyoming,Uinta,2018,273,237,36,0,0,0,0,93,54,40,0,2,175,0,0,96
1037,Wyoming,Weston,2018,252,207,44,1,0,0,0,101,54,44,0,0,246,6,0,0

In [19]:
s = df.groupby(["State", "Year"])["Max AQI", "Median AQI"].mean()

Empty DataFrame
Columns: [State, Year, Max_AQI, Median_AQI]
Index: []

In [35]:
s.to_csv("annual_aqi_by_state.csv")

                   Max AQI  Median AQI
State     Year
Alabama   1999  144.954545   47.590909
          2000  152.391304   49.217391
          2001  136.045455   42.727273
          2002  143.869565   41.521739
          2003  133.200000   42.400000
          2004  123.760000   42.400000
          2005  125.541667   43.666667
          2006  127.333333   44.291667
          2007  151.190476   48.047619
          2008  112.421053   44.578947
          2009   97.789474   39.473684
          2010  110.736842   46.263158
          2011  111.526316   42.789474
          2012  110.235294   40.176471
          2013   86.055556   37.166667
          2014   93.333333   38.166667
          2015  105.722222   39.333333
          2016  111.444444   39.388889
          2017  104.666667   38.277778
          2018   98.176471   38.176471
Alaska    1999  103.333333   21.833333
          2000  114.166667   22.666667
          2001   81.500000   19.625000
          2002   90.714286   21.000000
          2003  141.285714   17.857143
          2004  160.100000   15.300000
          2005   87.555556   16.222222
          2006   95.000000   17.625000
          2007   89.875000   16.875000
          2008   83.888889   14.222222
...                    ...         ...
Wisconsin 2009  118.031250   36.093750
          2010  117.515152   37.454545
          2011  124.466667   37.200000
          2012  140.000000   36.343750
          2013   96.848485   34.454545
          2014  115.148148   37.185185
          2015  110.392857   36.321429
          2016  119.000000   34.642857
          2017  100.678571   35.678571
          2018  118.142857   40.642857
Wyoming   1999  111.214286   22.071429
          2000   93.214286   20.785714
          2001   94.142857   23.642857
          2002   98.933333   22.466667
          2003   90.200000   21.400000
          2004  133.500000   20.714286
          2005   88.200000   21.600000
          2006  119.933333   25.000000
          2007   98.176471   29.294118
          2008  108.333333   29.666667
          2009   95.777778   27.722222
          2010   86.105263   29.157895
          2011  100.210526   32.421053
          2012  126.578947   34.789474
          2013  109.777778   36.777778
          2014   95.263158   35.105263
          2015  110.263158   34.789474
          2016   95.944444   37.277778
          2017  169.411765   38.470588
          2018   96.777778   39.388889

[1087 rows x 2 columns]