In [93]:
import pandas as pd
import numpy as np
import re

In [94]:
df_sheet1 = pd.read_csv('seds.csv')

In [95]:
df_sheet1.head()

,year,msn,state_name,state_code,description,energy_bin,value,unit
0,1960,ABICB,Alaska,AK,Aviation gasoline blending components consumed...,Petroleum,0.0,Billion Btu
1,1961,ABICB,Alaska,AK,Aviation gasoline blending components consumed...,Petroleum,0.0,Billion Btu
2,1962,ABICB,Alaska,AK,Aviation gasoline blending components consumed...,Petroleum,0.0,Billion Btu
3,1963,ABICB,Alaska,AK,Aviation gasoline blending components consumed...,Petroleum,0.0,Billion Btu
4,1964,ABICB,Alaska,AK,Aviation gasoline blending components consumed...,Petroleum,0.0,Billion Btu

In [96]:
df_sheet1['msn'].unique()

array(['ABICB', 'ABICP', 'ARICB', 'ARICD', 'ARICP', 'ARICV', 'ARTCB',
       'ARTCD', 'ARTCP', 'ARTCV', 'ARTXB', 'ARTXD', 'ARTXP', 'ARTXV',
       'AVACB', 'AVACD', 'AVACP', 'AVACV', 'AVTCB', 'AVTCD', 'AVTCP',
       'AVTCV', 'AVTXB', 'AVTXD', 'AVTXP', 'AVTXV', 'BMTCB', 'BQICB',
       'BQICP', 'BQTCB', 'BQTCP', 'BYICB', 'BYICP', 'BYTCB', 'BYTCP',
       'CLACB', 'CLACD', 'CLACK', 'CLACP', 'CLACV', 'CLCCB', 'CLCCD',
       'CLCCP', 'CLCCV', 'CLEIB', 'CLEID', 'CLEIK', 'CLEIP', 'CLEIV',
       'CLHCK', 'CLICB', 'CLICD', 'CLICP', 'CLICV', 'CLISB', 'CLKCB',
       'CLKCD', 'CLKCK', 'CLKCP', 'CLKCV', 'CLOCB', 'CLOCD', 'CLOCK',
       'CLOCP', 'CLOCV', 'CLOSB', 'CLPRB', 'CLPRK', 'CLPRP', 'CLRCB',
       'CLRCD', 'CLRCP', 'CLRCV', 'CLRFB', 'CLSCB', 'CLTCB', 'CLTCD',
       'CLTCP', 'CLTCV', 'CLTXB', 'CLTXD', 'CLTXP', 'CLTXV', 'COICB',
       'COICP', 'COPRK', 'DFACB', 'DFACD', 'DFACP', 'DFACV', 'DFCCB',
       'DFCCD', 'DFCCP', 'DFCCV', 'DFEIB', 'DFEID', 'DFEIP', 'DFEIV',
       'DFICB', 'DFICD', 'DFICP', 'DFICV', 'DFISB', 'DFRCB', 'DFRCD',
       'DFRCP', 'DFRCV', 'DFRFB', 'DFSCB', 'DFTCB', 'DFTCD', 'DFTCP',
       'DFTCV', 'DFTXB', 'DFTXD', 'DFTXP', 'DFTXV', 'ELEXB', 'ELEXD',
       'ELEXP', 'ELEXV', 'ELIMB', 'ELIMD', 'ELIMP', 'ELIMV', 'ELISB',
       'ELISP', 'ELNIB', 'ELNIP', 'EMACB', 'EMACV', 'EMCCB', 'EMCCV',
       'EMFDB', 'EMICB', 'EMICV', 'EMLCB', 'EMTCB', 'EMTCV', 'ENACP',
       'ENCCP', 'ENICP', 'ENPRP', 'ENTCP', 'EQICB', 'EQICP', 'EQTCB',
       'EQTCP', 'ESACB', 'ESACD', 'ESACP', 'ESACV', 'ESCCB', 'ESCCD',
       'ESCCP', 'ESCCV', 'ESICB', 'ESICD', 'ESICP', 'ESICV', 'ESISB',
       'ESRCB', 'ESRCD', 'ESRCP', 'ESRCV', 'ESRFB', 'ESSCB', 'ESTCB',
       'ESTCD', 'ESTCP', 'ESTCV', 'ESTXB', 'ESTXD', 'ESTXP', 'ESTXV',
       'EYICB', 'EYICP', 'EYTCB', 'EYTCP', 'FFTCB', 'FNICB', 'FNICD',
       'FNICP', 'FNICV', 'FOICB', 'FOICD', 'FOICP', 'FOICV', 'FSICB',
       'FSICD', 'FSICP', 'FSICV', 'GDPRV', 'GDPRX', 'GECCB', 'GEEGB',
       'GEEGP', 'GEICB', 'GERCB', 'GETCB', 'GETXB', 'HLACB', 'HLACD',
       'HLACP', 'HLACV', 'HLCCB', 'HLCCD', 'HLCCP', 'HLCCV', 'HLICB',
       'HLICD', 'HLICK', 'HLICP', 'HLICV', 'HLISB', 'HLRCB', 'HLRCD',
       'HLRCP', 'HLRCV', 'HLRFB', 'HLSCB', 'HLTCB', 'HLTCD', 'HLTCK',
       'HLTCP', 'HLTCV', 'HLTXB', 'HLTXD', 'HLTXP', 'HLTXV', 'HYCCB',
       'HYCCP', 'HYEGB', 'HYEGP', 'HYICB', 'HYICP', 'HYTCB', 'HYTCP',
       'HYTXB', 'HYTXP', 'IQICB', 'IQICP', 'IQTCB', 'IQTCP', 'IYICB',
       'IYICP', 'IYTCB', 'IYTCP', 'JFACB', 'JFACD', 'JFACP', 'JFACV',
       'JFTCB', 'JFTCD', 'JFTCP', 'JFTCV', 'JFTXB', 'JFTXD', 'JFTXP',
       'JFTXV', 'KSCCB', 'KSCCD', 'KSCCP', 'KSCCV', 'KSICB', 'KSICD',
       'KSICP', 'KSICV', 'KSRCB', 'KSRCD', 'KSRCP', 'KSRCV', 'KSTCB',
       'KSTCD', 'KSTCP', 'KSTCV', 'KSTXB', 'KSTXD', 'KSTXP', 'KSTXV',
       'LOACB', 'LOCCB', 'LOICB', 'LORCB', 'LOTCB', 'LOTXB', 'LUACB',
       'LUACD', 'LUACP', 'LUACV', 'LUICB', 'LUICD', 'LUICP', 'LUICV',
       'LUTCB', 'LUTCD', 'LUTCP', 'LUTCV', 'LUTXB', 'LUTXD', 'LUTXP',
       'LUTXV', 'MBICB', 'MBICP', 'MGACB', 'MGACD', 'MGACP', 'MGACV',
       'MGCCB', 'MGCCD', 'MGCCP', 'MGCCV', 'MGICB', 'MGICD', 'MGICP',
       'MGICV', 'MGTCB', 'MGTCD', 'MGTCP', 'MGTCV', 'MGTPV', 'MGTXB',
       'MGTXD', 'MGTXP', 'MGTXV', 'MMTCB', 'MSICB', 'MSICD', 'MSICP',
       'MSICV', 'NAICB', 'NAICP', 'NGACB', 'NGACD', 'NGACP', 'NGACV',
       'NGASB', 'NGCCB', 'NGCCD', 'NGCCP', 'NGCCV', 'NGEIB', 'NGEID',
       'NGEIK', 'NGEIP', 'NGEIV', 'NGICB', 'NGICD', 'NGICP', 'NGICV',
       'NGISB', 'NGLPB', 'NGMPB', 'NGMPK', 'NGMPP', 'NGPZB', 'NGRCB',
       'NGRCD', 'NGRCP', 'NGRCV', 'NGRFB', 'NGSCB', 'NGTCB', 'NGTCD',
       'NGTCK', 'NGTCP', 'NGTCV', 'NGTXB', 'NGTXD', 'NGTXK', 'NGTXP',
       'NGTXV', 'NNTCB', 'NUEGB', 'NUEGD', 'NUEGP', 'NUEGV', 'NUETB',
       'NUETD', 'NUETP', 'NUETV', 'OHICD', 'OHICV', 'OPICB', 'OPICD',
       'OPICP', 'OPICV', 'OPISB', 'OPSCB', 'OPTCB', 'OPTCD', 'OPTCP',
       'OPTCV', 'OPTXB', 'OPTXD', 'OPTXP', 'OPTXV', 'P1ICB', 'P1ICD',
       'P1ICP', 'P1ICV', 'P1ISB', 'P1SCB', 'P1TCB', 'P1TCD', 'P1TCP',
       'P1TCV', 'P1TXB', 'P1TXD', 'P1TXP', 'P1TXV', 'P5RFB', 'PAACB',
       'PAACD', 'PAACP', 'PAACV', 'PACCB', 'PACCD', 'PACCP', 'PACCV',
       'PAEIB', 'PAEID', 'PAEIP', 'PAEIV', 'PAICB', 'PAICD', 'PAICP',
       'PAICV', 'PAISB', 'PAPRB', 'PAPRP', 'PARCB', 'PARCD', 'PARCP',
       'PARCV', 'PASCB', 'PATCB', 'PATCD', 'PATCP', 'PATCV', 'PATXB',
       'PATXD', 'PATXP', 'PATXV', 'PCCCB', 'PCCCD', 'PCCCP', 'PCCCV',
       'PCEIB', 'PCEID', 'PCEIP', 'PCEIV', 'PCICB', 'PCICD', 'PCICP',
       'PCICV', 'PCISB', 'PCRFB', 'PCSCB', 'PCTCB', 'PCTCD', 'PCTCP',
       'PCTCV', 'PCTXB', 'PCTXD', 'PCTXP', 'PCTXV', 'PEACD', 'PEACV',
       'PEASB', 'PECCD', 'PECCV', 'PECSB', 'PEEID', 'PEEIV', 'PEICD',
       'PEICV', 'PEISB', 'PERCD', 'PERCV', 'PERSB', 'PESCB', 'PETCD',
       'PETCV', 'PETXD', 'PETXV', 'PLICB', 'PLICP', 'PMTCB', 'PPICB',
       'PPICP', 'PPTCB', 'PPTCP', 'PQACB', 'PQACD', 'PQACP', 'PQACV',
       'PQCCB', 'PQCCD', 'PQCCP', 'PQCCV', 'PQICB', 'PQICD', 'PQICP',
       'PQICV', 'PQISB', 'PQRCB', 'PQRCD', 'PQRCP', 'PQRCV', 'PQRFB',
       'PQSCB', 'PQTCB', 'PQTCD', 'PQTCP', 'PQTCV', 'PQTXB', 'PQTXD',
       'PQTXP', 'PQTXV', 'PYICB', 'PYICP', 'PYTCB', 'PYTCP', 'REPRB',
       'RETCB', 'RFACB', 'RFACD', 'RFACP', 'RFACV', 'RFCCB', 'RFCCD',
       'RFCCP', 'RFCCV', 'RFEIB', 'RFEID', 'RFEIP', 'RFEIV', 'RFICB',
       'RFICD', 'RFICP', 'RFICV', 'RFISB', 'RFRFB', 'RFSCB', 'RFTCB',
       'RFTCD', 'RFTCP', 'RFTCV', 'RFTXB', 'RFTXD', 'RFTXP', 'RFTXV',
       'ROPRB', 'SFCCB', 'SFEIB', 'SFINB', 'SFRCB', 'SFTCB', 'SGICB',
       'SGICP', 'SNICB', 'SNICD', 'SNICP', 'SNICV', 'SOCCB', 'SOCCP',
       'SOEGB', 'SOEGP', 'SOICB', 'SOICP', 'SOR7P', 'SORCB', 'SOTCB',
       'SOTGP', 'SOTXB', 'TEACB', 'TEACD', 'TEACV', 'TEAPB', 'TECCB',
       'TECCD', 'TECCV', 'TECPB', 'TEEIB', 'TEGDS', 'TEICB', 'TEICD',
       'TEICV', 'TEIPB', 'TEPFB', 'TEPRB', 'TERCB', 'TERCD', 'TERCV',
       'TERFB', 'TERPB', 'TETCB', 'TETCD', 'TETCV', 'TETGR', 'TETPB',
       'TETPV', 'TETXB', 'TETXD', 'TETXV', 'TNACB', 'TNASB', 'TNCCB',
       'TNCSB', 'TNICB', 'TNISB', 'TNRCB', 'TNRSB', 'TNSCB', 'TNTXB',
       'TPOPP', 'UOICB', 'UOICP', 'USICB', 'USICP', 'WDCCB', 'WDEIB',
       'WDEXB', 'WDICB', 'WDPRB', 'WDRCB', 'WDRCD', 'WDRCP', 'WDRCV',
       'WDRSB', 'WDRXB', 'WDTCB', 'WSCCB', 'WSEIB', 'WSICB', 'WSTCB',
       'WWCCB', 'WWCCD', 'WWCCV', 'WWCSB', 'WWCXB', 'WWEIB', 'WWEID',
       'WWEIV', 'WWICB', 'WWICD', 'WWICV', 'WWISB', 'WWIXB', 'WWSCB',
       'WWTCB', 'WWTCD', 'WWTCV', 'WWTXB', 'WWTXD', 'WWTXV', 'WXICB',
       'WXICD', 'WXICP', 'WXICV', 'WYCCB', 'WYCCP', 'WYEGB', 'WYEGP',
       'WYICB', 'WYICP', 'WYTCB', 'WYTCP', 'WYTXB', 'WYTXP', 'CCEXB',
       'CCEXD', 'CCEXP', 'CCEXV', 'CCIMB', 'CCIMD', 'CCIMP', 'CCIMV',
       'CCNIB', 'CCNIP', 'CCNIV', 'DFTCK', 'ENTCK', 'FFETK', 'MBTCK',
       'MGTCK', 'NUETK', 'PAACK', 'PACCK', 'PAEIK', 'PAICK', 'PARCK',
       'PATCK', 'PCCTK', 'PCMKK'], dtype=object)

In [97]:
min(df_sheet1['year']),max(df_sheet1['year'])

(1960, 2017)

In [98]:
df = df_sheet1[(df_sheet1['year']>= 2000)&(df_sheet1['year'] <=2016)].reset_index()

In [99]:
df.head()

,index,year,msn,state_name,state_code,description,energy_bin,value,unit
0,40,2000,ABICB,Alaska,AK,Aviation gasoline blending components consumed...,Petroleum,84.0,Billion Btu
1,41,2001,ABICB,Alaska,AK,Aviation gasoline blending components consumed...,Petroleum,134.0,Billion Btu
2,42,2002,ABICB,Alaska,AK,Aviation gasoline blending components consumed...,Petroleum,164.0,Billion Btu
3,43,2003,ABICB,Alaska,AK,Aviation gasoline blending components consumed...,Petroleum,165.0,Billion Btu
4,44,2004,ABICB,Alaska,AK,Aviation gasoline blending components consumed...,Petroleum,233.0,Billion Btu

In [65]:
#Renew_consumption = ['NUTCB','GETCB','HYTCB','SOTCB','WYTCB','WWTCB'] 
# nuclear, geothermal, hydroelectric, solar, wind, wood and Biomass
#Non_renew_consumption = ['PATCB','CLTCB','MGTCB']
#Petroleum, Coal, Motor

In [71]:
idx_renew =(df['msn'] == 'NUTCB') | (df['msn'] == 'GETCB') | (df['msn']=='HYTCB')|(df['msn']=='SOTCB')|(df['msn']=='WYTCB')|(df['msn']=='WWTCB')
renew_df = df[idx_renew]

idx_Non_renew =(df['msn'] == 'PATCB') | (df['msn'] == 'CLTCB') | (df['msn']=='MGTCB')|(df['msn']=='SOTCB')
nonrenew_df = df[idx_Non_renew]

In [73]:
nonrenew_df.head()

,index,year,msn,state_name,state_code,description,energy_bin,value,unit
1262,3686,1999,CLTCB,Alaska,AK,Coal total consumption,Coal,16394.0,Billion Btu
1263,3687,2000,CLTCB,Alaska,AK,Coal total consumption,Coal,16455.0,Billion Btu
1264,3688,2001,CLTCB,Alaska,AK,Coal total consumption,Coal,15911.0,Billion Btu
1265,3689,2002,CLTCB,Alaska,AK,Coal total consumption,Coal,16429.0,Billion Btu
1266,3690,2003,CLTCB,Alaska,AK,Coal total consumption,Coal,12552.0,Billion Btu

In [74]:
df.energy_bin.unique()

array(['Petroleum', 'Renewable', 'Natural Gas', 'Coal', 'Electricity',
       'Aggregate', 'Nuclear'], dtype=object)

In [81]:
idx = (df['energy_bin']=='Renewable') & (df['unit'] =='Billion Btu' )
df[idx]['msn'].unique()

array(['BMTCB', 'EMACB', 'EMCCB', 'EMFDB', 'EMICB', 'EMLCB', 'EMTCB',
       'EYICB', 'EYTCB', 'GECCB', 'GEEGB', 'GEICB', 'GERCB', 'GETCB',
       'GETXB', 'HYCCB', 'HYEGB', 'HYICB', 'HYTCB', 'HYTXB', 'REPRB',
       'RETCB', 'ROPRB', 'SOCCB', 'SOEGB', 'SOICB', 'SORCB', 'SOTCB',
       'SOTXB', 'WDCCB', 'WDEIB', 'WDEXB', 'WDICB', 'WDPRB', 'WDRCB',
       'WDRSB', 'WDRXB', 'WDTCB', 'WSCCB', 'WSEIB', 'WSICB', 'WSTCB',
       'WWCCB', 'WWCSB', 'WWCXB', 'WWEIB', 'WWICB', 'WWISB', 'WWIXB',
       'WWSCB', 'WWTCB', 'WWTXB', 'WYCCB', 'WYEGB', 'WYICB', 'WYTCB',
       'WYTXB'], dtype=object)

In [61]:
# Non-Renewable energy Code:

Energy_code = df['msn']
#list non-renewable energy
#Non_Rew = ['BM', 'BQ', 'BY', 'EL', 'EM', 'EN', 'EQ', 'EY', 'GE', 'HY', 'IQ', 'IY', 'LO', 'NU', 'PL'] 

Rew = 'RE' #renewable energy code
Total = 'TE' # total
pattern_rew = r'\w{4}V$' #renewable expenditure
pattern_total = r'^TE\w{2}V$' # total energy expenditure
renew_col = []
non_new_col = []
for u in Energy_code.unique():
    if re.findall(pattern_rew, u) != [] :
        renew_col.append(u)
    else:
        continue
for u in Energy_code.unique():
    if re.findall(pattern_total, u) != [] :
        non_new_col.append(u)
    else:
        continue

In [110]:
df_renew = df[df['msn'] == 'RETCB'] # use renewable energy total consumption cost in BTU
df_renew.sort_values(['state_code','year'], inplace = True)
df_renew.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 884 entries, 8287 to 557947
Data columns (total 9 columns):
index          884 non-null int64
year           884 non-null int64
msn            884 non-null object
state_name     884 non-null object
state_code     884 non-null object
description    884 non-null object
energy_bin     884 non-null object
value          884 non-null float64
unit           884 non-null object
dtypes: float64(1), int64(2), object(6)
memory usage: 69.1+ KB

/Users/sarahyu/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [111]:
df_total = df[df['msn'] == 'TETCB'] # get total energy total consumption cost in BTU
df_total.sort_values(['state_code','year'], inplace = True)
df_total.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 884 entries, 9511 to 559171
Data columns (total 9 columns):
index          884 non-null int64
year           884 non-null int64
msn            884 non-null object
state_name     884 non-null object
state_code     884 non-null object
description    884 non-null object
energy_bin     884 non-null object
value          884 non-null float64
unit           884 non-null object
dtypes: float64(1), int64(2), object(6)
memory usage: 69.1+ KB

/Users/sarahyu/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [112]:
df_renew['Non-renewable Consumption(BTU)'] = np.array(df_total['value']) - np.array(df_renew['value'])
df_renew.info

/Users/sarahyu/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

<bound method DataFrame.info of           index  year    msn     state_name state_code  \
8287      25240  2000  RETCB         Alaska         AK
8288      25241  2001  RETCB         Alaska         AK
8289      25242  2002  RETCB         Alaska         AK
8290      25243  2003  RETCB         Alaska         AK
8291      25244  2004  RETCB         Alaska         AK
8292      25245  2005  RETCB         Alaska         AK
8293      25246  2006  RETCB         Alaska         AK
8294      25247  2007  RETCB         Alaska         AK
8295      25248  2008  RETCB         Alaska         AK
8296      25249  2009  RETCB         Alaska         AK
8297      25250  2010  RETCB         Alaska         AK
8298      25251  2011  RETCB         Alaska         AK
8299      25252  2012  RETCB         Alaska         AK
8300      25253  2013  RETCB         Alaska         AK
8301      25254  2014  RETCB         Alaska         AK
8302      25255  2015  RETCB         Alaska         AK
8303      25256  2016  RETCB         Alaska         AK
19056     58119  2000  RETCB        Alabama         AL
19057     58120  2001  RETCB        Alabama         AL
19058     58121  2002  RETCB        Alabama         AL
19059     58122  2003  RETCB        Alabama         AL
19060     58123  2004  RETCB        Alabama         AL
19061     58124  2005  RETCB        Alabama         AL
19062     58125  2006  RETCB        Alabama         AL
19063     58126  2007  RETCB        Alabama         AL
19064     58127  2008  RETCB        Alabama         AL
19065     58128  2009  RETCB        Alabama         AL
19066     58129  2010  RETCB        Alabama         AL
19067     58130  2011  RETCB        Alabama         AL
19068     58131  2012  RETCB        Alabama         AL
...         ...   ...    ...            ...        ...
547166  1670595  2004  RETCB  West Virginia         WV
547167  1670596  2005  RETCB  West Virginia         WV
547168  1670597  2006  RETCB  West Virginia         WV
547169  1670598  2007  RETCB  West Virginia         WV
547170  1670599  2008  RETCB  West Virginia         WV
547171  1670600  2009  RETCB  West Virginia         WV
547172  1670601  2010  RETCB  West Virginia         WV
547173  1670602  2011  RETCB  West Virginia         WV
547174  1670603  2012  RETCB  West Virginia         WV
547175  1670604  2013  RETCB  West Virginia         WV
547176  1670605  2014  RETCB  West Virginia         WV
547177  1670606  2015  RETCB  West Virginia         WV
547178  1670607  2016  RETCB  West Virginia         WV
557931  1703470  2000  RETCB        Wyoming         WY
557932  1703471  2001  RETCB        Wyoming         WY
557933  1703472  2002  RETCB        Wyoming         WY
557934  1703473  2003  RETCB        Wyoming         WY
557935  1703474  2004  RETCB        Wyoming         WY
557936  1703475  2005  RETCB        Wyoming         WY
557937  1703476  2006  RETCB        Wyoming         WY
557938  1703477  2007  RETCB        Wyoming         WY
557939  1703478  2008  RETCB        Wyoming         WY
557940  1703479  2009  RETCB        Wyoming         WY
557941  1703480  2010  RETCB        Wyoming         WY
557942  1703481  2011  RETCB        Wyoming         WY
557943  1703482  2012  RETCB        Wyoming         WY
557944  1703483  2013  RETCB        Wyoming         WY
557945  1703484  2014  RETCB        Wyoming         WY
557946  1703485  2015  RETCB        Wyoming         WY
557947  1703486  2016  RETCB        Wyoming         WY

                               description energy_bin     value         unit  \
8287    Renewable energy total consumption  Renewable   12375.0  Billion Btu
8288    Renewable energy total consumption  Renewable   17439.0  Billion Btu
8289    Renewable energy total consumption  Renewable   18257.0  Billion Btu
8290    Renewable energy total consumption  Renewable   19598.0  Billion Btu
8291    Renewable energy total consumption  Renewable   18857.0  Billion Btu
8292    Renewable energy total consumption  Renewable   15866.0  Billion Btu
8293    Renewable energy total consumption  Renewable   13298.0  Billion Btu
8294    Renewable energy total consumption  Renewable   14037.0  Billion Btu
8295    Renewable energy total consumption  Renewable   12913.0  Billion Btu
8296    Renewable energy total consumption  Renewable   15685.0  Billion Btu
8297    Renewable energy total consumption  Renewable   16537.0  Billion Btu
8298    Renewable energy total consumption  Renewable   15762.0  Billion Btu
8299    Renewable energy total consumption  Renewable   17719.0  Billion Btu
8300    Renewable energy total consumption  Renewable   18664.0  Billion Btu
8301    Renewable energy total consumption  Renewable   19826.0  Billion Btu
8302    Renewable energy total consumption  Renewable   19209.0  Billion Btu
8303    Renewable energy total consumption  Renewable   19428.0  Billion Btu
19056   Renewable energy total consumption  Renewable  263303.0  Billion Btu
19057   Renewable energy total consumption  Renewable  252817.0  Billion Btu
19058   Renewable energy total consumption  Renewable  253570.0  Billion Btu
19059   Renewable energy total consumption  Renewable  284700.0  Billion Btu
19060   Renewable energy total consumption  Renewable  293216.0  Billion Btu
19061   Renewable energy total consumption  Renewable  279765.0  Billion Btu
19062   Renewable energy total consumption  Renewable  266305.0  Billion Btu
19063   Renewable energy total consumption  Renewable  228635.0  Billion Btu
19064   Renewable energy total consumption  Renewable  237119.0  Billion Btu
19065   Renewable energy total consumption  Renewable  273619.0  Billion Btu
19066   Renewable energy total consumption  Renewable  264186.0  Billion Btu
19067   Renewable energy total consumption  Renewable  276863.0  Billion Btu
19068   Renewable energy total consumption  Renewable  263095.0  Billion Btu
...                                    ...        ...       ...          ...
547166  Renewable energy total consumption  Renewable   20758.0  Billion Btu
547167  Renewable energy total consumption  Renewable   28719.0  Billion Btu
547168  Renewable energy total consumption  Renewable   28818.0  Billion Btu
547169  Renewable energy total consumption  Renewable   26783.0  Billion Btu
547170  Renewable energy total consumption  Renewable   33508.0  Billion Btu
547171  Renewable energy total consumption  Renewable   50820.0  Billion Btu
547172  Renewable energy total consumption  Renewable   48580.0  Billion Btu
547173  Renewable energy total consumption  Renewable   50679.0  Billion Btu
547174  Renewable energy total consumption  Renewable   50561.0  Billion Btu
547175  Renewable energy total consumption  Renewable   60422.0  Billion Btu
547176  Renewable energy total consumption  Renewable   56677.0  Billion Btu
547177  Renewable energy total consumption  Renewable   51359.0  Billion Btu
547178  Renewable energy total consumption  Renewable   51271.0  Billion Btu
557931  Renewable energy total consumption  Renewable   15011.0  Billion Btu
557932  Renewable energy total consumption  Renewable   14656.0  Billion Btu
557933  Renewable energy total consumption  Renewable   12275.0  Billion Btu
557934  Renewable energy total consumption  Renewable   11635.0  Billion Btu
557935  Renewable energy total consumption  Renewable   14033.0  Billion Btu
557936  Renewable energy total consumption  Renewable   19272.0  Billion Btu
557937  Renewable energy total consumption  Renewable   19517.0  Billion Btu
557938  Renewable energy total consumption  Renewable   18888.0  Billion Btu
557939  Renewable energy total consumption  Renewable   22412.0  Billion Btu
557940  Renewable energy total consumption  Renewable   34967.0  Billion Btu
557941  Renewable energy total consumption  Renewable   45646.0  Billion Btu
557942  Renewable energy total consumption  Renewable   61389.0  Billion Btu
557943  Renewable energy total consumption  Renewable   54961.0  Billion Btu
557944  Renewable energy total consumption  Renewable   54518.0  Billion Btu
557945  Renewable energy total consumption  Renewable   55495.0  Billion Btu
557946  Renewable energy total consumption  Renewable   48467.0  Billion Btu
557947  Renewable energy total consumption  Renewable   54453.0  Billion Btu

        Non-renewable Consumption(BTU)
8287                          729763.0
8288                          718381.0
8289                          714716.0
8290                          713902.0
8291                          756181.0
8292                          781834.0
8293                          733018.0
8294                          709032.0
8295                          637507.0
8296                          624009.0
8297                          638058.0
8298                          639237.0
8299                          632816.0
8300                          599257.0
8301                          585091.0
8302                          598663.0
8303                          580522.0
19056                        1848414.0
19057                        1665221.0
19058                        1725285.0
19059                        1685515.0
19060                        1790249.0
19061                        1785217.0
19062                        1836198.0
19063                        1857616.0
19064                        1766644.0
19065                        1527319.0
19066                        1677188.0
19067                        1639111.0
19068                        1626674.0
...                                ...
547166                        715756.0
547167                        708879.0
547168                        731949.0
547169                        763246.0
547170                        743081.0
547171                        655669.0
547172                        699418.0
547173                        684908.0
547174                        679414.0
547175                        691209.0
547176                        724682.0
547177                        724429.0
547178                        715910.0
557931                        413098.0
557932                        423837.0
557933                        426551.0
557934                        449744.0
557935                        436739.0
557936                        436832.0
557937                        460922.0
557938                        504821.0
557939                        516113.0
557940                        489313.0
557941                        495660.0
557942                        496283.0
557943                        496007.0
557944                        485682.0
557945                        481949.0
557946                        455732.0
557947                        447971.0

[884 rows x 10 columns]>

In [115]:
df_renew = df_renew.rename(index=str,columns={"value": "Renewable Consumption(BTU)"})
df_renew.reset_index()

,level_0,index,year,msn,state_name,state_code,description,energy_bin,Renewable Consumption(BTU),unit,Non-renewable Consumption(BTU)
0,8287,25240,2000,RETCB,Alaska,AK,Renewable energy total consumption,Renewable,12375.0,Billion Btu,729763.0
1,8288,25241,2001,RETCB,Alaska,AK,Renewable energy total consumption,Renewable,17439.0,Billion Btu,718381.0
2,8289,25242,2002,RETCB,Alaska,AK,Renewable energy total consumption,Renewable,18257.0,Billion Btu,714716.0
3,8290,25243,2003,RETCB,Alaska,AK,Renewable energy total consumption,Renewable,19598.0,Billion Btu,713902.0
4,8291,25244,2004,RETCB,Alaska,AK,Renewable energy total consumption,Renewable,18857.0,Billion Btu,756181.0
5,8292,25245,2005,RETCB,Alaska,AK,Renewable energy total consumption,Renewable,15866.0,Billion Btu,781834.0
6,8293,25246,2006,RETCB,Alaska,AK,Renewable energy total consumption,Renewable,13298.0,Billion Btu,733018.0
7,8294,25247,2007,RETCB,Alaska,AK,Renewable energy total consumption,Renewable,14037.0,Billion Btu,709032.0
8,8295,25248,2008,RETCB,Alaska,AK,Renewable energy total consumption,Renewable,12913.0,Billion Btu,637507.0
9,8296,25249,2009,RETCB,Alaska,AK,Renewable energy total consumption,Renewable,15685.0,Billion Btu,624009.0
10,8297,25250,2010,RETCB,Alaska,AK,Renewable energy total consumption,Renewable,16537.0,Billion Btu,638058.0
11,8298,25251,2011,RETCB,Alaska,AK,Renewable energy total consumption,Renewable,15762.0,Billion Btu,639237.0
12,8299,25252,2012,RETCB,Alaska,AK,Renewable energy total consumption,Renewable,17719.0,Billion Btu,632816.0
13,8300,25253,2013,RETCB,Alaska,AK,Renewable energy total consumption,Renewable,18664.0,Billion Btu,599257.0
14,8301,25254,2014,RETCB,Alaska,AK,Renewable energy total consumption,Renewable,19826.0,Billion Btu,585091.0
15,8302,25255,2015,RETCB,Alaska,AK,Renewable energy total consumption,Renewable,19209.0,Billion Btu,598663.0
16,8303,25256,2016,RETCB,Alaska,AK,Renewable energy total consumption,Renewable,19428.0,Billion Btu,580522.0
17,19056,58119,2000,RETCB,Alabama,AL,Renewable energy total consumption,Renewable,263303.0,Billion Btu,1848414.0
18,19057,58120,2001,RETCB,Alabama,AL,Renewable energy total consumption,Renewable,252817.0,Billion Btu,1665221.0
19,19058,58121,2002,RETCB,Alabama,AL,Renewable energy total consumption,Renewable,253570.0,Billion Btu,1725285.0
20,19059,58122,2003,RETCB,Alabama,AL,Renewable energy total consumption,Renewable,284700.0,Billion Btu,1685515.0
21,19060,58123,2004,RETCB,Alabama,AL,Renewable energy total consumption,Renewable,293216.0,Billion Btu,1790249.0
22,19061,58124,2005,RETCB,Alabama,AL,Renewable energy total consumption,Renewable,279765.0,Billion Btu,1785217.0
23,19062,58125,2006,RETCB,Alabama,AL,Renewable energy total consumption,Renewable,266305.0,Billion Btu,1836198.0
24,19063,58126,2007,RETCB,Alabama,AL,Renewable energy total consumption,Renewable,228635.0,Billion Btu,1857616.0
25,19064,58127,2008,RETCB,Alabama,AL,Renewable energy total consumption,Renewable,237119.0,Billion Btu,1766644.0
26,19065,58128,2009,RETCB,Alabama,AL,Renewable energy total consumption,Renewable,273619.0,Billion Btu,1527319.0
27,19066,58129,2010,RETCB,Alabama,AL,Renewable energy total consumption,Renewable,264186.0,Billion Btu,1677188.0
28,19067,58130,2011,RETCB,Alabama,AL,Renewable energy total consumption,Renewable,276863.0,Billion Btu,1639111.0
29,19068,58131,2012,RETCB,Alabama,AL,Renewable energy total consumption,Renewable,263095.0,Billion Btu,1626674.0
...,...,...,...,...,...,...,...,...,...,...,...
854,547166,1670595,2004,RETCB,West Virginia,WV,Renewable energy total consumption,Renewable,20758.0,Billion Btu,715756.0
855,547167,1670596,2005,RETCB,West Virginia,WV,Renewable energy total consumption,Renewable,28719.0,Billion Btu,708879.0
856,547168,1670597,2006,RETCB,West Virginia,WV,Renewable energy total consumption,Renewable,28818.0,Billion Btu,731949.0
857,547169,1670598,2007,RETCB,West Virginia,WV,Renewable energy total consumption,Renewable,26783.0,Billion Btu,763246.0
858,547170,1670599,2008,RETCB,West Virginia,WV,Renewable energy total consumption,Renewable,33508.0,Billion Btu,743081.0
859,547171,1670600,2009,RETCB,West Virginia,WV,Renewable energy total consumption,Renewable,50820.0,Billion Btu,655669.0
860,547172,1670601,2010,RETCB,West Virginia,WV,Renewable energy total consumption,Renewable,48580.0,Billion Btu,699418.0
861,547173,1670602,2011,RETCB,West Virginia,WV,Renewable energy total consumption,Renewable,50679.0,Billion Btu,684908.0
862,547174,1670603,2012,RETCB,West Virginia,WV,Renewable energy total consumption,Renewable,50561.0,Billion Btu,679414.0
863,547175,1670604,2013,RETCB,West Virginia,WV,Renewable energy total consumption,Renewable,60422.0,Billion Btu,691209.0
864,547176,1670605,2014,RETCB,West Virginia,WV,Renewable energy total consumption,Renewable,56677.0,Billion Btu,724682.0
865,547177,1670606,2015,RETCB,West Virginia,WV,Renewable energy total consumption,Renewable,51359.0,Billion Btu,724429.0
866,547178,1670607,2016,RETCB,West Virginia,WV,Renewable energy total consumption,Renewable,51271.0,Billion Btu,715910.0
867,557931,1703470,2000,RETCB,Wyoming,WY,Renewable energy total consumption,Renewable,15011.0,Billion Btu,413098.0
868,557932,1703471,2001,RETCB,Wyoming,WY,Renewable energy total consumption,Renewable,14656.0,Billion Btu,423837.0
869,557933,1703472,2002,RETCB,Wyoming,WY,Renewable energy total consumption,Renewable,12275.0,Billion Btu,426551.0
870,557934,1703473,2003,RETCB,Wyoming,WY,Renewable energy total consumption,Renewable,11635.0,Billion Btu,449744.0
871,557935,1703474,2004,RETCB,Wyoming,WY,Renewable energy total consumption,Renewable,14033.0,Billion Btu,436739.0
872,557936,1703475,2005,RETCB,Wyoming,WY,Renewable energy total consumption,Renewable,19272.0,Billion Btu,436832.0
873,557937,1703476,2006,RETCB,Wyoming,WY,Renewable energy total consumption,Renewable,19517.0,Billion Btu,460922.0
874,557938,1703477,2007,RETCB,Wyoming,WY,Renewable energy total consumption,Renewable,18888.0,Billion Btu,504821.0
875,557939,1703478,2008,RETCB,Wyoming,WY,Renewable energy total consumption,Renewable,22412.0,Billion Btu,516113.0
876,557940,1703479,2009,RETCB,Wyoming,WY,Renewable energy total consumption,Renewable,34967.0,Billion Btu,489313.0
877,557941,1703480,2010,RETCB,Wyoming,WY,Renewable energy total consumption,Renewable,45646.0,Billion Btu,495660.0
878,557942,1703481,2011,RETCB,Wyoming,WY,Renewable energy total consumption,Renewable,61389.0,Billion Btu,496283.0
879,557943,1703482,2012,RETCB,Wyoming,WY,Renewable energy total consumption,Renewable,54961.0,Billion Btu,496007.0
880,557944,1703483,2013,RETCB,Wyoming,WY,Renewable energy total consumption,Renewable,54518.0,Billion Btu,485682.0
881,557945,1703484,2014,RETCB,Wyoming,WY,Renewable energy total consumption,Renewable,55495.0,Billion Btu,481949.0
882,557946,1703485,2015,RETCB,Wyoming,WY,Renewable energy total consumption,Renewable,48467.0,Billion Btu,455732.0
883,557947,1703486,2016,RETCB,Wyoming,WY,Renewable energy total consumption,Renewable,54453.0,Billion Btu,447971.0

In [120]:
df_renew.drop(columns=['index', 'msn', 'description','energy_bin'],inplace=True)

In [121]:
df_renew.head()

,year,state_name,state_code,Renewable Consumption(BTU),unit,Non-renewable Consumption(BTU)
8287,2000,Alaska,AK,12375.0,Billion Btu,729763.0
8288,2001,Alaska,AK,17439.0,Billion Btu,718381.0
8289,2002,Alaska,AK,18257.0,Billion Btu,714716.0
8290,2003,Alaska,AK,19598.0,Billion Btu,713902.0
8291,2004,Alaska,AK,18857.0,Billion Btu,756181.0

In [122]:
df_renew.to_csv('energy_consumption.csv')

In [92]:
Years = df_renew['year'].unique()
States = df_renew['state_code'].unique()
States

array(['AK', 'AL', 'AR', 'AZ', 'CA', 'CO', 'CT', 'DC', 'DE', 'FL', 'GA',
       'HI', 'IA', 'ID', 'IL', 'IN', 'KS', 'KY', 'LA', 'MA', 'MD', 'ME',
       'MI', 'MN', 'MO', 'MS', 'MT', 'NC', 'ND', 'NE', 'NH', 'NJ', 'NM',
       'NV', 'NY', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX',
       'US', 'UT', 'VA', 'VT', 'WA', 'WI', 'WV', 'WY'], dtype=object)